question_data = [
    {"text": "A slug's blood is green.", "answer": "True"},
    {"text": "The loudest animal is the African Elephant.", "answer": "False"},
    {"text": "Approximately one quarter of human bones are in the feet.", "answer": "True"},
    {"text": "The total surface area of a human lungs is the size of a football pitch.", "answer": "True"},
    {"text": "In West Virginia, USA, if you accidentally hit an animal with your car, you are free to take it home to eat.", "answer": "True"},
    {"text": "In London, UK, if you happen to die in the House of Parliament, you are entitled to a state funeral.", "answer": "False"},
    {"text": "It is illegal to pee in the Ocean in Portugal.", "answer": "True"},
    {"text": "You can lead a cow down stairs but not up stairs.", "answer": "False"},
    {"text": "Google was originally called 'Backrub'.", "answer": "True"},
    {"text": "Buzz Aldrin's mother's maiden name was 'Moon'.", "answer": "True"},
    {"text": "No piece of square dry paper can be folded in half more than 7 times.", "answer": "False"},
    {"text": "A few ounces of chocolate can to kill a small dog.", "answer": "True"},
    {"text":"The Republic of Malta is the smallest microstate worldwide.","answer":"False"},
    {"text":"In &quot;Super Mario Bros.&quot;, the clouds and bushes have the same artwork and are just different colors.","answer":"True"},
    {"text":"The United States Department of Homeland Security was formed in response to the September 11th attacks.","answer":"True"},
    {"text":"In Kingdom Hearts the Paopu fruit is said to intertwine the destinies for two people forever.","answer":"True"},
    {"text":"Ottawa is the capital of Canada.","answer":"True"},
    {"text":"United States President John F. Kennedy was assassinated during his presidential motorcade in Atlanta, Georgia on November 22nd, 1963.","answer":"False"},
    {"text":"The full English name of the car manufacturer BMW is Bavarian Motor Works","answer":"True"},
    {"text":"&quot;Elementary, my dear Watson&quot; is a phrase that is never truly said within the Conan Doyle books of Sherlock Holmes.","answer":"True"},
    {"text":"In Sonic the Hedgehog universe, Tails&#039; real name is Miles Prower.","answer":"True"},
    {"text":"Stevie Wonder&#039;s real name is Stevland Hardaway Morris.","answer":"True"},
    {"text":"Marilyn Monroe was born on July 1, 1926.","answer":"False"},
    {"text":"In Battlestar Galactica (2004), Cylons were created by man as cybernetic workers and soldiers.","answer":"True"},
    {"text":"The Killer Whale is considered a type of dolphin.","answer":"True"},
    {"text":"&quot;Foodfight!&quot; earned less than $80,000 at box office.","answer":"True"},
    {"text":"In 1993, Prince changed his name to an unpronounceable symbol because he was unhappy with his contract with Warner Bros.","answer":"True"},
    {"text":"The 2011 movie &quot;The Adventures of Tintin&quot; was directed by Steven Spielberg.","answer":"True"},
    {"text":"&quot;The Simpsons&quot; family is named after creator Matt Groening&#039;s real family.","answer":"True"},
    {"text":"The internet browser Firefox is named after the Red Panda.","answer":"True"}]